Minor fixes
AgoraIO/Docs-Help pull request #5
Opened 2022-10-03 06:48 UTC by Kishan-Dhakan

- Resolves https://github.com/AgoraIO/Docs-Source/issues/467

2022-10-04 16:19 UTC, billy-the-fish requested changes
Nearly there.

2022-10-05 13:35 UTC, Kishan-Dhakan commented on general-product-inquiry/agora_product.mdx
> +- [Video Calling](https://docs.agora.io/en/video-calling/overview/product-overview)
Resolved

2022-10-05 13:41 UTC, Kishan-Dhakan commented on general-product-inquiry/capacity.mdx
> +- To minimize bandwidth consumption and ensure smooth communication in a real-time video streaming scenario with multiple users, Agora recommends referring to <a href="https://docs.agora.io/en/Intera
Used the multi channel doc relative instead now

2022-10-05 13:44 UTC, Kishan-Dhakan commented on integration-issues/string.mdx
> +- <a href="https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms">Cloud Recording</a >
Fixed

2022-10-07 07:29 UTC, billy-the-fish commented
@Kishan-Dhakan , can you quickly check the links in https://docs.agora.io/en/help/quality-issues/video_blank and https://docs.agora.io/en/help/general-product-inquiry/browser_support please. If they are not good, can you update please. Plus go through https://docs.google.com/spreadsheets/d/1kGLHc-FkXO_paRkFQA6BlawKw3zqtAdzUC55sahR-AI/edit#gid=1874725026 and fix all links. Thanks in advance.

2022-10-07 08:03 UTC, Kishan-Dhakan reviewed
Links checked

2022-10-07 08:03 UTC, Kishan-Dhakan commented on integration-issues/string.mdx
> +- <a href="/en/3.x/video-calling/reference/agora-console-rest-api">Console RESTful API</a >
Works

2022-10-07 13:59 UTC, billy-the-fish approved these changes
LGTM.

2022-10-07 13:59 UTC, merged